import { AppTheme } from "@/src/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 16,
  },
  // Dropdown Styles
  dropdownContainer: {
    flex: 1,
    position: "relative",
  },
  dropdown: {
    height: 60,
    borderColor: "#E5E7EB",
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: "white",
    opacity: 0, // Hide the default dropdown input
  },
  dropdownSelectedContent: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 40,
    bottom: 0,
    justifyContent: "center",
    paddingLeft: 44,
    paddingRight: 8,
  },
  dropdownIcon: {
    marginRight: 8,
  },
  dropdownArrow: {
    position: "absolute",
    right: 12,
    top: "50%",
    marginTop: -9,
  },
  dropdownPlaceholder: {
    fontSize: 14,
    color: "#9CA3AF",
  },
  dropdownSelected: {
    fontSize: 14,
    color: "transparent", // Hide the selected text (we'll show our custom view instead)
  },
  dropdownItem: {
    padding: 12,
    flexDirection: "column",
    alignItems: "flex-start",
  },
  dropdownItemText: {
    fontSize: 14,
    color: "#111827",
  },
  dropdownItemSubtext: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  // Period Dropdown
  periodDropdownContainer: {
    width: 120,
  },
  periodDropdown: {
    height: 36,
    borderColor: "#E5E7EB",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: "white",
  },
  periodPlaceholder: {
    fontSize: 14,
    color: "#374151",
  },
  periodSelected: {
    fontSize: 14,
    color: "#374151",
  },
  periodDropdownIcon: {
    marginLeft: 8,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  dropdownButton: {
    flexDirection: "row",
    alignItems: "center",
  },
  dropdownTitle: { fontWeight: "600", fontSize: 14, marginLeft: 6 },
  dropdownSubtitle: { fontSize: 12, color: "#9CA3AF", marginLeft: 6 },
  statsCard: {
    flexDirection: "row",
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 10,
    justifyContent: "space-around",
  },
  statCol: { alignItems: "center" },
  statValue: { fontSize: 16, color: "#111827", fontWeight: "600" },
  activeValue: { color: "#2563EB" },
  statLabel: { fontSize: 12, color: "#6B7280", marginTop: 4 },
  netWorthRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
  },
  netWorthTitle: { fontSize: 16, fontWeight: "600", color: "#111827" },
  periodButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  periodText: { fontSize: 13, color: "#111827", marginRight: 2 },
  netWorthValue: {
    fontSize: 28,
    fontWeight: "700",
    color: "#111827",
    marginTop: 4,
    marginBottom: 10,
  },
  // +++ ADDED style for the chart to remove default margins +++
  chartStyle: {
    marginVertical: 8,
    // The library adds some padding, so a negative margin helps align it
    marginLeft: -16,
  },
  percentRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 10,
  },
  percentCol: { alignItems: "center" },
  circle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
  },
  percentLabel: { fontSize: 12, color: "#6B7280" },
  percentValue: { fontSize: 13, fontWeight: "600" },
  assetsCard: {
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    padding: 16,
    marginTop: 10,
    position: "relative",
  },
  assetsHeader: { flexDirection: "row", justifyContent: "space-between" },
  assetTitle: { fontSize: 15, fontWeight: "600", color: "#111827" },
  assetValue: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111827",
    marginVertical: 6,
  },
  assetProgressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  subLabel: { fontSize: 13, color: "#6B7280" },
  assetAmount: { fontSize: 15, fontWeight: "600", color: "#111827" },
  progressBar: {
    flexDirection: "row",
    height: 8,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "#E5E7EB",
  },
  verifiedBar: { backgroundColor: "#10B981" },
  unverifiedBar: { backgroundColor: "#EF4444" },
  totalAssetBadge: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 4,
    borderColor: "#EF4444",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFF",
  },
  totalAssetText: {
    fontSize: 12,
    textAlign: "center",
    color: "#111827",
    fontWeight: "500",
  },
  tabRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    alignItems: "center",
  },
  tabs: { flexDirection: "row" },
  viewAll: { fontSize: 13, color: "#2563EB" },
  tabButton: {
    backgroundColor: "#E5E7EB",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginRight: 8,
  },
  activeTab: { backgroundColor: "#2563EB" },
  tabText: { color: "#6B7280", fontSize: 14, fontWeight: "500" },
  activeTabText: { color: "#FFF" },
  roomCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#FAFAFA",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    padding: 16,
    marginVertical: 6,
  },
  roomTitle: { fontSize: 15, fontWeight: "600", marginBottom: 4 },
  roomMembers: { fontSize: 14 },
  roomItems: {
    fontSize: 13,
    color: "#6B7280",
    textAlign: "right",
    fontWeight: "500",
  },
  addButton: {
    backgroundColor: "#EEF2FF",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginVertical: 20,
  },
  addText: { color: "#2563EB", fontWeight: "600", fontSize: 15 },
});
