-- ================================================================
-- DOMAIN  : Households
-- TABLE   : public.households + public.addresses
-- FILE    : rpc/households/01_create_household.sql
--
-- PURPOSE : Create a new household group, link the creator to it,
--           and save their address (city, state, country) — all in
--           a single atomic transaction.
--           Called from: CreateHousehold.tsx → handleContinue().
--
-- AUTH    : Any authenticated user can create a household.
--           They automatically become the first member.
--
-- USAGE   :
--   SELECT * FROM create_household(
--     p_name    := 'Team WordNinja',
--     p_city    := 'Mumbai',
--     p_state   := 'Maharashtra',
--     p_country := 'India'
--   );
-- ================================================================

CREATE OR REPLACE FUNCTION public.create_household(
    p_name    TEXT,
    p_city    TEXT DEFAULT NULL,
    p_state   TEXT DEFAULT NULL,
    p_country TEXT DEFAULT 'India'
)
RETURNS public.households AS $$
DECLARE
    new_hh  public.households;
    v_uid   UUID := auth.uid();
BEGIN
    -- ── AUTH CHECK ────────────────────────────────────────────
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'Access denied: authentication required';
    END IF;
    -- ─────────────────────────────────────────────────────────

    -- 1. Create the household (join_code auto-generated by default)
    INSERT INTO public.households (name, created_by)
    VALUES (p_name, v_uid)
    RETURNING * INTO new_hh;

    -- 2. Link the creator's profile to this household
    UPDATE public.profiles
    SET household_id = new_hh.id,
        updated_at   = now()
    WHERE id = v_uid;

    -- 3. Save their address and associate with this household
    INSERT INTO public.addresses (user_id, household_id, city, state, country, is_primary)
    VALUES (v_uid, new_hh.id, p_city, p_state, p_country, TRUE)
    ON CONFLICT DO NOTHING;

    RETURN new_hh;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
